const routes = {
  home: "/",
  search: "/search",
  diamondCalculate: "/diamond-calculate",
  diamondCheck: "/diamond-check",
  diamondCheckDetails: "/diamond-check/:certificateId",
  diamondDetail: "/diamond-detail",
  diamondService: "/diamond-service",
  diamonValuationRequest: "/diamond-valuation-request",
  prices: "/prices",
  education: "/education",
  educationCertificate: "/education/certificate",
  educationShape: "/education/shape",
  educationCarat: "/education/carat",
  educationColor: "/education/color",
  educationCut: "/education/cut",
  educationClarity: "/education/clarity",
  login: "/login",
  logout: "/logout",
  consultingStaff: "/consulting-staff",
  valuationStaff: "/valuation-staff",
  dashboard: "/dashboard",
};
export default routes;
