const routes = {
    home: "/",
    diamondCalculate: "/diamond-calculate",
    diamondCheck: "/diamond-check",
    diamondCheckDetails: "/diamond-check/:valuationResultId",
    diamondDetail: "/diamond-detail",
    diamondService: "/diamond-service",
    diamondValuationRequest: "/diamond-valuation-request",
    prices: "/prices",
    educationCertificate: "/education/certificate",
    educationShape: "/education/shape",
    educationCarat: "/education/carat",
    educationColor: "/education/color",
    educationCut: "/education/cut",
    educationClarity: "/education/clarity",
    login: "/login",
    logout: "/logout",
    error: "*",
    aboutUs: "/aboutUs",
    dashboard: "/dashboard",
    dasboardNotification: "/dashboard/notifications",
    dashboardPrices: "/dashboard/prices",
    dashboardAppoint: "/dashboard/appointments",
    dashboardSearch: "/dashboard/search",
    dashboardRequest: "/dashboard/request",
    dashboardSetting: "/dashboard/setting",
    dashboardTransaction: "/dashboard/transaction",
    manageAccount: "/dashboard/manage-account",
    pendingRequest: "/dashboard/pending-request",
    processRequest: "/dashboard/process-request",
    sealingLetter: "/dashboard/sealing-letter",
    commitment: "/dashboard/commitment",
    valuationDiamond: "/dashboard/valuation-diamond",
    manageService: "/dashboard/manage-service",
    activate: "/activate/:email",
};
export default routes;
