const routes = {
  home: "/",
  search: "/search",
  diamondCalculate: "/diamond-calculate",
  diamondCheck: "/diamond-check",
  diamondCheckDetails: "/diamond-check/:certificateId",
  diamondDetail: "/diamond-detail",
  diamondService: "/diamond-service",
  diamondValuationRequest: "/diamond-valuation-request/:id",
  prices: "/prices",
  educationCertificate: "/education/certificate",
  educationShape: "/education/shape",
  educationCarat: "/education/carat",
  educationColor: "/education/color",
  educationCut: "/education/cut",
  educationClarity: "/education/clarity",
  login: "/login",
  logout: "/logout",
  consultingStaff: "/consulting-staff",
  error: "*",
  valuationStaff: "/valuation-staff",
  aboutUs: "/about",
  // ConsultingStaff's DashBoard
  consulting_dashboard: "/consulting-staff-dashboard",
  consulting_dasboardNotification: "/consulting-staff-dashboard/notifications",
  consulting_dashboardPrices: "/consulting-staff-dashboard/prices",
  consulting_dashboardAppoint: "/consulting-staff-dashboard/appointments",
  consulting_dashboardSearch: "/consulting-staff-dashboard/search",
  consulting_dashboardRequest: "/consulting-staff-dashboard/request",
  // Customer's Dashboard
  dashboard: "/dashboard",
  dasboardNotification: "/dashboard/notifications",
  dashboardPrices: "/dashboard/prices",
  dashboardAppoint: "/dashboard/appointments",
  dashboardSearch: "/dashboard/search",
  dashboardRequest: "/dashboard/request",
  // Admin's Dashboard
  admin: "/admin",
  manager: "/manager",
};
export default routes;
