USE [master]
GO

/****** Object:  Database [Diamond]    Script Date: 19/05/2024 11:56:00 AM ******/
CREATE DATABASE [Diamond]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Diamond', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.BAOTHU\MSSQL\DATA\Diamond.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Diamond_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.BAOTHU\MSSQL\DATA\Diamond_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Diamond].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Diamond] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Diamond] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Diamond] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Diamond] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Diamond] SET ARITHABORT OFF 
GO

ALTER DATABASE [Diamond] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Diamond] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Diamond] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Diamond] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Diamond] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Diamond] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Diamond] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Diamond] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Diamond] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Diamond] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Diamond] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Diamond] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Diamond] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Diamond] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Diamond] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Diamond] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Diamond] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Diamond] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Diamond] SET  MULTI_USER 
GO

ALTER DATABASE [Diamond] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Diamond] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Diamond] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Diamond] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Diamond] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Diamond] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Diamond] SET QUERY_STORE = ON
GO

ALTER DATABASE [Diamond] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Diamond] SET  READ_WRITE 
GO

