export const title = [
  "1. Round Brilliant Cut Diamonds",
  "2. Princess Cut Diamond",
  "3. Emerald Cut Diamond",
  "4. Cushion Cut Diamond",
  "5. Asscher Cut Diamond",
  "6. Pear Shaped Diamond",
  "7. Oval Diamond",
  "8. Heart Shaped Diamond",
  "9. Radiant Cut Diamond",
  "10. Marquise Diamond",
  "11. Baguette Diamond",
  "12. Trillion Diamond",
];
export const image = [
  "https://www.diamonds.pro/wp-content/uploads/2021/01/Round-cut.jpg",
  "https://www.diamonds.pro/wp-content/uploads/2021/05/Princess-cut.png",
  "https://www.diamonds.pro/wp-content/uploads/2021/01/Emerald-cut.jpg",
  "https://www.diamonds.pro/wp-content/uploads/2021/01/cushion-cut.jpg",
  "https://www.diamonds.pro/wp-content/uploads/2021/01/Asscher-cut.jpg",
  "https://www.diamonds.pro/wp-content/uploads/2021/05/Pear-Shape-300x202.png",
  "https://www.diamonds.pro/wp-content/uploads/2021/05/Oval-300x240.png",
  "https://www.diamonds.pro/wp-content/uploads/2021/01/Heath-shape.jpg",
  "https://www.diamonds.pro/wp-content/uploads/2021/01/Radiant-Cut.png",
  "https://www.diamonds.pro/wp-content/uploads/2021/01/marquise-cut.jpg",
  "https://www.diamonds.pro/wp-content/uploads/2017/01/Diamond_Baguette.png",
  "https://www.diamonds.pro/wp-content/uploads/2017/01/Diamond_Trillion.png",
];
export const description = [
  "As the leading diamond ring shape in terms of popularity, the round brilliant cut represents over two thirds of the diamonds sold. In 1919, Marcel Tolkowsky published, “Diamond Design: A Study of the Reflection and Refraction of Light in Diamond,” which explained the ideal angles for a diamond to produce the highest level of brilliance and fire. His work created a surge in the round brilliant cut’s popularity, which remains consistent today. The round diamond’s refined shape allows for maximum reflection of light, contributing to its incredible brilliance. Round brilliant cuts have 58 facets (including the culet).",
  "This fancy cut shape is second in diamond popularity after the round brilliant cut. It’s created from the inverted pyramid of the rough diamond stone. Traditionally square, the princess cut diamond achieves greater brilliance and fire than other similarly shaped diamonds. Rectangular princess cuts are also available.",
  "Using the technique originally designed to cut emeralds, this diamond ring shape comes rightly by its name. With its large table surface, the emerald cut diamond offers abundant reflections through its long, straight lines or ‘steps.’ Emerald cuts are prominent in both square and rectangle.",
  "The cushion cut diamond gets its name from the combination of a square or rectangular shape with rounded edges, making it look like a pillow or cushion. Due to its precise bending and dispersion of light, the cushion cut beams with fire.",
  "First produced by the Asscher Brothers of Holland in 1902, the asscher cut diamond regained popularity in 2002 after its one hundredth anniversary and a slight modification to the cut technique. As a dazzling alternative to the emerald cut, the asscher cut diamond hosts a smaller table and more layered facets. Brilliance is achieved through light reflection among the square facets seen underneath the table. The asscher cut’s trimmed corners give it extra style and stability.",
  "With a rounded side that narrows to a distinct point, the pear shaped diamond is an elegant, timeless choice. If purchasing for a ring, the pointed end will point toward the heart of the wearer. Symmetry is critical to the appearance of a pear shaped diamond so it shimmers evenly.",
  "Showcasing similar brilliance and fire to the round cut, the oval cut diamond is an exquisite choice for those who wish to wear a unique shape. The oval’s elongated silhouette offers a large appearance compared to other shapes of the same carat.",
  "A prominent symbol of love, the heart shaped diamond boasts an exquisite figure that can be set in a ring, pendant or other jewelry piece. Heart shaped diamonds range in slenderness and width, selected primarily on personal preference. A well-cut heart shaped diamond should be symmetrical, so it appears balanced and full. The point or cleft of the diamond should be distinct.",
  "Radiant cut diamonds gained their popularity in the 1980s due to their dazzling brilliance which is only exceeded by the round brilliant. The radiant cut is an enchanting choice due to its numerous facets found in the pavilion and crown. These features provide a high level of both brilliance and fire. Its cropped corners also make it a delightful match for pairing with rounded or square diamonds.",
  "Originally requested by King Louis XIV to mimic the shape of his mistress’ mouth, the marquise diamond has remained a flattering and delightful choice for several centuries. The narrow body shape of the marquise resembles the shape of an elongated eye. Its stunning large crown is complementary to wearers as it makes the finger appear longer and more slender.",
  "Showcasing 24 parallel facets, the baguette diamond hosts long, parallel lines and remarkable clarity. Rectangular in shape with step cutting, baguettes make for vibrant ring center pieces and graceful side stones.",
  "Trillion diamonds, also known as trilliant diamonds, are incredibly enchanting and unique. Different than round, square or rectangular shapes, the trillion almost always makes an impression. With their rich brilliance and deep fire, trillions diverge from popular shapes yet are just as exquisite.",
];
export const lengthToWidthRatio = [
  "For the most aesthetic diamonds, choose a length to width ratio of 1.0-1.03.",
  "As noted with asscher cuts, a length to width ratio of 1.0-1.05 offers a square shape to the naked eye. For a rectangular princess cut, 1.5-2.0 is a suitable range.",
  "A traditional emerald cut ratio ranges from 1.30 to 1.60, with the most popular choice being 1.50.",
  "Cushions are often square, but can be rectangular as well. For the square shape, keep the ratio between 1.0 -1.09. Slight rectangles usually range from 1.15-1.25 in ratio.",
  "A length to width ratio for a square asscher should fall between 1.0-1.05 to maintain a square look for the naked eye.",
  "The classic length to width ratio ranges from 1.45-1.75. Reviewing a variety of ratios will give you an idea of personal preference. You may wish, for example, for a wider or more narrow shape.",
  "While always dependent on personal preference, the oval diamond is often appealing in a ratio of 1.30-1.50.",
  "An ideal length to width ratio is 1.00. The lower the ratio, the more “chubby” the heart will look. If the ratio is above 1.10, the heart will appear more stretched (elongated, tall and thin).",
  "A 1.0-1.05 is an ideal range for a square cut. Rectangular shapes may have a ratio of up to 2.0.",
  "The marquise’s unique structure offers a length to width range of 1.85 to 2.1.",
  "Based on personal preference and use of the baguette diamond, length to width ratios range from 1.50-2.40.",
  "The ideal length to width ratio for a trillion is 1.0-1.10.",
];
export const proTip = [
  "The cut quality of a round brilliant diamond significantly impacts its beauty and is perhaps the most important element when selecting a diamond. In addition to reviewing ratings or GIA reports, look at the diamond firsthand or ask for the help of an expert. Some expensive diamonds with higher ratings may have more noticeable inclusions than certain less expensive diamonds.",
  "To prevent damage to the corners, a princess cut diamond should be set with prongs on all four corners. Inclusions will generally be hidden by the prongs, so it’s acceptable to choose a princess cut with inclusions toward the edges.",
  "Because of its magnificently large table, inclusions may be more noticeable in an emerald cut. For this reason, we advise seeking a VS1 or VS2 for the emerald shape. Normally an SI1 has a good chance of not being visible. But, as you can see in this diamond from James Allen, that is rarely the case in emerald cuts.",
  "As a general guideline, try to stick to cushions with a depth under 70% and a table under 70%. This will ensure brilliance and fire is maintained throughout the depth of the diamond.",
  "When it comes to color, asscher cuts don’t mask the color of the diamond’s rough material as well as other cuts like the round brilliant and princess cut. Asschers are cut for their clarity and lustre—so nothing is hidden. For this reason, we recommend buying a minimum of an H color in the asscher cut.",
  "When selecting your pear shaped diamond, watch for the severity of the bowtie—the dark area running across the center of the diamond. All pear shaped diamonds, and other fancy elongated shapes, usually have a bowtie. Review the diamond or have an expert assist you in determining if the bowtie is too prominent within the piece.",
  "Similar to the pear shaped cut, look for the severity of the bowtie in an oval. The bowtie is the dark area running across the center of the diamond. Review each diamond or have an expert assist you with determining if the bowtie is too prominent within the piece.",
  "Due to its form, the heart shaped cut comes best in a higher carat, such as 1 or 2. If using a smaller carat weight, a three-prong setting will aid in highlighting the outline of the heart.",
  "The color differences in radiant cuts are harder to perceive than in other diamond ring shapes. An H color grade is usually sufficient in radiants, allowing you to use your budget on other aspects of the cut quality.",
  "Due to its long shape, symmetry is important when selecting a marquise diamond. Ensure the two pointed ends align almost perfectly with each other. When a marquise diamond is set, two prongs will hold the pointed ends to prevent chipping. It’s worth noting that inclusions near the tips of the marquise will likely be hidden by these prongs.",
  "Usually available in smaller sizes, the baguette is a perfect accent to another stone or as a part of a wedding band. Several baguettes can be placed next to each other for a large diamond array. Because of the baguette’s clearness, ensure no noticeable inclusions are contained within the diamond.",
  "Trillions make for prominent centerpieces of an engagement ring or as complementary side stones. When setting a trillion diamond, ensure the edges are protected with prongs. If a trillion has inclusions near its points, they will likely be hidden by prongs or a jewelry border.",
];
export const strongTips = [
  "The round brilliant cut is popular for many reasons, one being that it provides exceptional brilliance and a classic, ageless look. Round brilliant cut diamonds are stunning choices for engagement rings, necklaces and other fine pieces.",
  "The princess cut allows for a square outline while still offering nearly the same brilliance as the round diamond. Due to the larger yield maintained from cutting for a princess, the price per carat is usually much lower than the round cut.",
  "Most notably, the emerald cut showcases size better than other diamonds of the same carat. Emerald cuts are a premium choice for those desiring a larger piece without an enormous price tag.",
  "With many cut options, choosing a cushion diamond offers creativity and personalization. Cushions also have the luxurious appeal of a classic fashion along with modern fire and flair.",
  "The asscher cut’s deep pavilion and precision creates an enamoring appeal. While similar to the emerald cut, the asscher tends to offer a bit more sparkle, due to its high crown and 58 facets.",
  "A pear shaped diamond makes for an enchanting engagement ring. Because well-cut pear shapes are harder to find, it’s an exquisite alternative to traditional cuts like the round diamond. The pear shaped also hides inclusions well.",
  "This fancy length diamond is durable because it carries no pointed edges. Ovals also have a lower price point than round diamonds while still maintaining the curved shape.",
  "In addition to being a sign of romance, the heart shaped diamond requires a premium cut, prolonging and possibly increasing its value over time.",
  "Radiants are formed with many facets and angles, making them appear almost like cracked ice. Because of this, flaws and inclusions are easily hidden. The beveled corners of radiant cuts allow for more stability—making it a wise choice for those with an active lifestyle.",
  "The marquise’s elongated figure gives the appearance of a larger stone when compared to other shapes in the same carat. Making the fingers of the wearer look thinner and longer, the marquise shines brightly and is usually noticed for its unique shape.",
  "The long bar shape of the baguette offers exceptional size even at a low carat. Its clarity and appealing symmetry make it a classic and timeless diamond.",
  "The personality of the trillion is perhaps its strongest asset. The sharp, unique features create a dashing look, maximized by the trillion’s immense width. For this reason, trillions tend to look larger than other diamonds of the same carat weight.",
];
export const sampleCost = [
  "based on a 1.02 carat with an excellent cut, J color and SI1 clarity",
  "based on a 1.01 carat well cut, I color and a VVS2 clarity",
  "based on a 1.01 carat well cut, I color and a VVS1 clarity",
  "based on a 1.00 carat well cut, E color and a VS2 clarity",
  "based on a 1.01 carat well cut, I color and a VVS1 clarity",
  "based on a 1.01 carat well cut, E color and a SI1 clarity",
  "based on a 1.00 carat well cut, E color and a SI1 clarity",
  "based on a 1.01 carat well cut, H color and a VS2 clarity",
  "based on a 1.02 carat well cut, H color and a VS1 clarity",
  "based on a 1.03 carat well cut, H color and a VS1 clarity",
  "based on a 1.0 carat well cut, G color and a VS1 clarity",
  "based on a 1.0 carat well cut, G color and a VS1 clarity",
];
export const sampleCostPrice = [
  "2,810",
  "3,410",
  "3,200",
  "4,450",
  "2,780",
  "4,210",
  "4,400",
  "3,920",
  "3,330",
  "4,730",
  "3,200",
  "5,180",
];
export const whatToLookFor = [
  "Make sure the diamond shape needs to fit the style of setting you are going for.",
  " Some shapes are more brilliant than others. The round diamond is the most brilliant.",
];
export const whatToAvoid = [
  "If you are not 100% sure of your choice, avoid trendy cuts like marquise or heart shapes.",
  "Regardless of shape, the diamond needs to be well cut. For more info, read our article on diamond cut.",
];
